routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/test', function () {
	return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::resource('registration', 'RegistrationController');
	Route::resource('course', 'CourseController');
	Route::get('payment', 'PaymentController@index')->name('payment.index');
	Route::get('payment/{id}', 'PaymentController@edit')->name('payment.edit');
	Route::patch('payment/{id}', 'PaymentController@update')->name('payment.update');
	Route::delete('payment/{id}', 'PaymentController@destroy')->name('payment.destroy');
});

Route::group(['prefix'=>'member', 'middleware'=>['auth','role:member']], function () {
	Route::get('/registration', function(){
		return view('members.registration');
	});
	Route::get('/registration/view', 'RegistrationController@view')->name('regist.view');
	Route::post('/registration', 'RegistrationController@regist')->name('regist.store');

	Route::get('/payment', function(){
		return view('members.payment');
	});
	Route::get('/payment/view', 'PaymentController@view')->name('payment.view');
	Route::post('/payment', 'PaymentController@store')->name('payment.store');
});

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $fillable = ['registration_id','type','bank','name','amount','status'];

    public function registration()
    {
        return $this->belongsTo('App\Registration');
    }

    public static function statusList()
    {
        return [
            'pending' => 'Menunggu Konfirmasi',
            'verified' => 'Pembayaran Diterima'
        ];
    }

    public function getHumanStatusAttribute()
    {
        return static::statusList()[$this->status];
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Payment;
use DB;
use Session;

class PaymentController extends Controller
{
    /*method for show data*/
    public function index()
    {
    	$payments = Payment::with('registration')->get();

    	return view('payments.index')->with(compact('payments'));
    }

    public function edit($id)
    {
        $payment = Payment::findOrFail($id);

        return view('payments.edit')->with(compact('payment'));
    }

    public function update(Request $request,$id)
    {
        $this->validate($request, [
          'type' => 'required',
          'bank' => 'required',
          'name' => 'required',
          'status' => 'required',
        ]);

        $payment= Payment::findOrFail($id);
        $payment->update($request->all());

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil mengedit data"
        ]);

        return redirect()->route('payment.index');
    }

    public function destroy(Request $request, $id)
    {
        $payment = Payment::find($id);
        $photo = $payment->photo;
        if(!$payment->delete()) return redirect()->back();

        // handle hapus buku via ajax
        if ($request->ajax()) return response()->json(['id' => $id]);

        // hapus photo lama, jika ada
        if ($photo) {
            $old_photo = $payment->photo;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                . DIRECTORY_SEPARATOR . $payment->photo;

            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Data berhasil dihapus"
        ]);

        return redirect()->route('payment.index');
    }

    public function store(Request $request)
    {
    	$this->validate($request, [
          'type' => 'required',
          'bank' => 'required',
          'name' => 'required',
          'amount' => 'required',
          'photo' => 'image|max:2048',
        ]);

        $user_id = \Auth::user()->id;
        $registration = DB::table('registrations')->select('id')->where('user_id',$user_id)->first();

        $payment = Payment::create($request->except('photo','registration_id'));

        // isi field photo jika ada photo yang diupload
        if ($request->hasFile('photo')) {
            $uploaded_photo = $request->file('photo');

            // mengambil extension file
            $extension = $uploaded_photo->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;

            // memindahkan file ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
            $uploaded_photo->move($destinationPath, $filename);

            // mengisi field photo dengan filename yang baru dibuat
            $payment->photo = $filename;
        }

        //user_id sementara static
        $payment->registration_id = $registration->id;

        // save data
        $payment->save();
        
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Pembayaran Berhasil, silahkan tunggu konfirmasi dari kami."
        ]);

        return redirect()->route('home');
    }

    public function view()
    {
        $user_id = \Auth::user()->id;
        $registration = DB::table('registrations')->select('id')->where('user_id',$user_id)->first();
        if ($registration != null) {
            $payments = Payment::with('registration')->where('registration_id',$registration->id)->get();
        } else {
            $payments = Payment::where('registration_id',0)->get();
        }

        return view('members.payment_view')->with(compact('payments'));
    }
}

resources/views/payments/edit.blade.php
@extends('layouts.main')

@section('content')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Pembayaran</h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><i class="fa fa-dashboard"></i> Pembayaran</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">Edit Pembayaran</h3>

            <div class="box-tools pull-right">
              <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i></button>
              <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i></button>
            </div>
          </div>
          <div class="box-body">
            <form class="form-horizontal" action="{{route('payment.update',$payment->id)}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PATCH">

              <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                <label for="category_id" class="col-md-4 col-sm-4 col-xs-12 control-label">Jenis Pembayaran</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" name="type">
                        <option value="{{ $payment->type }}">{{ $payment->type }}</option>
                        <option value="">--Pilih Jenis Pembayaran--</option>
                        <option value="administrasi">Pembayaran Administrasi</option>
                    </select>
                    @if ($errors->has('type'))
                        <span class="help-block">
                            <strong>{{ $errors->first('type') }}</strong>
                        </span>
                    @endif
                </div>
              </div>

              <div class="form-group{{ $errors->has('bank') ? ' has-error' : '' }}">
                <label for="category_id" class="col-md-4 col-sm-4 col-xs-12 control-label">Metode Pembayaran</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" name="bank">
                        <option value="{{ $payment->bank }}">{{ $payment->bank }}</option>
                        <option value="">--Pilih Metode Pembayaran--</option>
                        <option value="transfer-bca">Transfer BCA</option>
                    </select>
                    @if ($errors->has('bank'))
                        <span class="help-block">
                            <strong>{{ $errors->first('bank') }}</strong>
                        </span>
                    @endif
                </div>
              </div>

              <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                  <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Atas Nama</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" name="name" value="{{ $payment->name }}">
                      @if ($errors->has('name'))
                          <span class="help-block">
                              <strong>{{ $errors->first('name') }}</strong>
                          </span>
                      @endif
                  </div>
              </div>

              <div class="form-group{{ $errors->has('amount') ? ' has-error' : '' }}">
                  <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Jumlah Bayar</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <input type="number" class="form-control" name="amount" value="{{ $payment->amount }}">
                      @if ($errors->has('amount'))
                          <span class="help-block">
                              <strong>{{ $errors->first('amount') }}</strong>
                          </span>
                      @endif
                  </div>
              </div>

              <div class="form-group{{ $errors->has('photo') ? ' has-error' : '' }}">
                  <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Bukti Pembayaran</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <input type="hidden" name="photo" value="{{ $payment->photo }}">
                      @if ($errors->has('photo'))
                          <span class="help-block">
                              <strong>{{ $errors->first('photo') }}</strong>
                          </span>
                      @endif
                      <div class="thumbnail">
                        <img src="{{ url('img',$payment->photo) }}" class="img-rounded">
                      </div>
                  </div>
              </div>

              <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
              <label for="category_id" class="col-md-4 col-sm-4 col-xs-12 control-label">Status</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                  <select class="form-control" name="status">
                      <option value="{{ $payment->status }}">{{ $payment->human_status }}</option>
                      <option value="">--Pilih Status--</option>
                      <option value="pending">Menunggu Konfirmasi</option>
                      <option value="verified">Telah Diverifikasi</option>
                  </select>
                  @if ($errors->has('status'))
                      <span class="help-block">
                          <strong>{{ $errors->first('status') }}</strong>
                      </span>
                  @endif
              </div>
            </div>
              
              <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                      <button type="submit" class="btn btn-primary">
                          Simpan
                      </button>
                  </div>
              </div>
            </form>
          </div>
          <!-- /.box-body -->
        </div>
      <!-- /.box -->
    </section>
  <!-- /.content -->
@endsection

resources/views/payments/index.blade.php
@extends('layouts.main')

@section('content')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Pembayaran</h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><i class="fa fa-dashboard"></i> Pembayaran</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
    @include('layouts._flash')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Data Pembayaran</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Kode Registrasi</th>
                    <th>Pembayaran</th>
                    <th>Bank</th>
                    <th>Jumlah Bayar</th>
                    <th>Status</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($payments as $key => $item)
                  <tr>
                    <td>{{ ++$key }}</td>
                    <td>{{ $item->registration->code }}</td>
                    <td>{{ $item->type }}</td>
                    <td>{{ $item->bank }}</td>
                    <td>{{ $item->amount }}</td>
                    <td>{{ $item->human_status }}</td>
                    <td>
                    <form action="{{ route('payment.destroy',$item->id) }}" method="post">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="delete">
                        <a class="btn btn-warning btn-xs" href="{{ route('payment.edit',$item->id) }}" title="Edit Data">Edit</a> |
                        <button type="submit" value="Delete" class="btn btn-danger btn-xs" title="Hapus Data">
                            Hapus
                        </button>
                    </form>
                    </td>
                  </tr>  
                  @endforeach
                </tbody>
              </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
    <!-- /.box -->
    </section>
  <!-- /.content -->
@endsection