routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/test', function () {
	return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::resource('registration', 'RegistrationController');
	Route::resource('course', 'CourseController');
	Route::get('payment', 'PaymentController@index')->name('payment.index');
	Route::get('payment/{id}', 'PaymentController@edit')->name('payment.edit');
	Route::patch('payment/{id}', 'PaymentController@update')->name('payment.update');
	Route::delete('payment/{id}', 'PaymentController@destroy')->name('payment.destroy');
});

Route::group(['prefix'=>'member', 'middleware'=>['auth','role:member']], function () {
	Route::get('/registration', function(){
		return view('members.registration');
	});
	Route::get('/registration/view', 'RegistrationController@view')->name('regist.view');
	Route::post('/registration', 'RegistrationController@regist')->name('regist.store');

	Route::get('/payment', function(){
		return view('members.payment');
	});
	Route::get('/payment/view', 'PaymentController@view')->name('payment.view');
	Route::post('/payment', 'PaymentController@store')->name('payment.store');
});

resources/views/courses/create.blade.php
@extends('layouts.main')

@section('content')
  <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Kursus</h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('course.index') }}"></i> Kursus</a></li>
        <li class="active"></i>Tambah Kursus</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Program Kursus</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <form class="form-horizontal" action="{{route('course.store')}}" method="post">
            {{ csrf_field() }}
            <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                <label for="title" class="col-md-4 col-sm-4 col-xs-12 control-label">Kode Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" name="code" value="{{ old('code') }}">

                    @if ($errors->has('code'))
                        <span class="help-block">
                            <strong>{{ $errors->first('code') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Nama Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('periode') ? ' has-error' : '' }}">
                <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Periode Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" name="periode" value="{{ old('periode') }}">
                    @if ($errors->has('periode'))
                        <span class="help-block">
                            <strong>{{ $errors->first('periode') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Harga Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" class="form-control" name="price" value="{{ old('price') }}">
                    @if ($errors->has('price'))
                        <span class="help-block">
                            <strong>{{ $errors->first('price') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Simpan
                    </button>
                </div>
            </div>
          </form>
        </div>
        <!-- /.box-body -->
      </div>
    <!-- /.box -->
    </section>
  <!-- /.content -->
@endsection

resources/views/courses/edit.blade.php
@extends('layouts.main')

@section('content')
  <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Kursus</h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('course.index') }}"></i> Kursus</a></li>
        <li class="active"></i>Edit Kursus</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Edit Program Kursus</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <form class="form-horizontal" action="{{route('course.update',$course->id)}}" method="post">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                <label for="title" class="col-md-4 col-sm-4 col-xs-12 control-label">Kode Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" name="code" value="{{ $course->code }}">

                    @if ($errors->has('code'))
                        <span class="help-block">
                            <strong>{{ $errors->first('code') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Nama Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" name="name" value="{{ $course->name }}">
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('periode') ? ' has-error' : '' }}">
                <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Periode Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" name="periode" value="{{ $course->periode }}">
                    @if ($errors->has('periode'))
                        <span class="help-block">
                            <strong>{{ $errors->first('periode') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Harga Program</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" class="form-control" name="price" value="{{ $course->price }}">
                    @if ($errors->has('price'))
                        <span class="help-block">
                            <strong>{{ $errors->first('price') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Simpan
                    </button>
                </div>
            </div>
          </form>
        </div>
        <!-- /.box-body -->
      </div>
    <!-- /.box -->
    </section>
  <!-- /.content -->
@endsection

resources/views/courses/index.blade.php
@extends('layouts.main')

@section('content')
  <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Kursus</h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"></i> Kursus</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
    @include('layouts._flash')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Daftar Program Kursus</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <p> <a class="btn btn-sm btn-primary" href="{{ route('course.create') }}">Tambah</a> </p>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Kode Program</th>
                    <th>Nama Program</th>
                    <th>Periode Kursus</th>
                    <th>Harga</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($courses as $key => $item)
                  <tr>
                    <td>{{ ++$key }}</td>
                    <td>{{ $item->code }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->periode }}</td>
                    <td>{{ $item->price }}</td>
                    <td>
                    <form action="{{ route('course.destroy', $item->id) }}" method="post">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="delete">
                        <a class="btn btn-warning btn-xs" href="{{ route('course.edit', $item->id) }}" title="Edit Data">Edit</a> |
                        <button type="submit" value="Delete" class="btn btn-danger btn-xs" title="Hapus Data">
                            Hapus
                        </button>
                    </form>
                    </td>
                  </tr>  
                  @endforeach
                </tbody>
              </table>
            </div> 
        </div>
        <!-- /.box-body -->
      </div>
    <!-- /.box -->
    </section>
  <!-- /.content -->
@endsection